print ("i will count my chickens:")
print ("hens",int(25+30/6),)
print ("rosters",100-25*3%4,)
print ("now i'll count the eggs:")
print (int(3+2+1-5+4%2-1/4+6),)
print ("What is 3+2?",3+2,)
print ("what is 5-7?",5-7,)
print ("Oh,that's why it's false .")
print("How About some more.")
print ("Is it greater?",5>-2)
print ("Is it greater or equal?",5>=-2,)
print ("Is it less or equal?",5<=-2,)

